name: Code checks

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  IMAGE_NAME: nice-resume

jobs:
  node_vulnerabilities:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup repository
        uses: ./.github/actions/setup_repo
      - name: Run Snyk to check for Node vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  docker_vulnerabilities:
    needs: container_build_push
    runs-on: ubuntu-24.04
    steps:
      - name: Run Snyk to check Docker image for vulnerabilities
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME:latest
