name: Code checks

on:
  push:
    branches: [$default-branch]
  pull_request:

defaults:
  run:
    shell: bash

env:
  A11Y_HOST: http://localhost:3000 # Nuxt preview default url:port

jobs:
  code_checks:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup repository
        uses: ./.github/actions/setup_repo
      - name: pnpm audit
        run: |
          pnpm audit > ./audit.log || true
          if ! [ "$(cat ./audit.log | wc -l)" = 1 ]; then
            echo "::warning::$(cat ./audit.log)"
          fi
          rm ./audit.log
      - name: Format
        run: pnpm run format:check:all
      - name: Lint
        run: pnpm run lint:check:all

  tests:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup repository
        uses: ./.github/actions/setup_repo
      - name: Run tests
        run: pnpm run test:unit

  pa11y-axe:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - name: Setup repository
        uses: ./.github/actions/setup_repo
      - name: Launch server
        run: pnpm run preview & pnpx wait-on $A11Y_HOST
      - name: Run pa11y
        run: |
          pnpx pa11y $A11Y_HOST \
            --runner axe \
            --runner htmlcs \
            --ignore 'color-contrast;link-in-text-block;WCAG2AA.Principle1.Guideline1_4.1_4_3.G18.Fail'

  # https://playwright.dev/docs/ci-intro
  # https://playwright.dev/docs/docker
  test-playwright:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    container:
      image: mcr.microsoft.com/playwright:v1.43.0-jammy
    steps:
      - uses: actions/checkout@v4
      - name: Setup repository
        uses: ./.github/actions/setup_repo
      - name: Install Playwright browsers
        run: pnpm exec playwright install --with-deps
      - name: Launch server
        run: pnpm run preview & pnpx wait-on $A11Y_HOST
      - name: Run Playwright tests
        run: pnpm exec playwright test
        env:
          HOME: /root
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
